### ISSUE TITLE
Prepare for CRAN release 

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizrdata#3]
Now that _prioritizr_ is on CRAN, we should prepare this package for release on CRAN too.

**Comment by ricschuster** [comment]
Good call. 
@ninamorrell, which parts of this package did you still have on your to-do list?

**Comment by ninamorrell** [comment]
As far as documentation, the only thing I hadn't finished was to run the makefile to get everything in place. Vignettes and documentation were finished, and it looks like the directory is complete now. The only other thing was putting plotted solutions in the Tasmania vignette, which I was having trouble with because of long run-times, but it looks like that's been resolved too. So nothing left on my to-do list!

**Comment by ricschuster** [comment]
Thanks very much Nina.

**Comment by ricschuster** [comment]
Checks passed, vignette examples tested, release candidate created, package submitted to CRAN.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
